### ISSUE TITLE
Telnet Connector throws error

### ISSUE THREAD

**Issue by sotoz** [jookies/jasmin-web#2]
When a successfull connection occurs on jcli through the TelnetConnector the system throws the following error:

```
Unhandled Error
Traceback (most recent call last):
Failure: twisted.conch.telnet.OptionRefused: twisted.conch.telnet.OptionRefused:'"'
```

This appears on the console of the logged in user in the box that runs jasmin although the remote telnet connection is working properly.

**Comment by farirat** [comment]
Hi @sotoz, that's because your telnet client is not negociating with jcli as if it were a real telnet console, that's why twisted.conch is claiming those errors.

Please consider reading this example: https://github.com/jookies/jasmin-monitoring/blob/master/jasmin/script/jasmin/jasmin_discover.py
Starting from line 87, you can see how it's connecting to jcli and setting a negociation callback, it's a python code but i guess you can find same tools in php.

Closing the issue as it's not a jCli bug.

**Comment by sotoz** [comment]
Yeap, its not a jcli bug but I have to find a better way to open a socket for telnet connection without triggering the twisted error. As there is no Telnet extension for php we have to emulate it as close as possible to avoid the error.

**Comment by farirat** [comment]
This seems a good one: https://github.com/jnorell/Net_Telnet/blob/master/Net/Telnet.php

**Comment by sotoz** [comment]
I have managed to make the errors disappear by removing the extra bytes that were sending during the connection. Now it works like a charm. I will update the branch with the new code.
